### PR TITLE
Add <t to aliases of <top

### LINKED ISSUE #850: add <t alias for <top
> <t for <top since a lot of ppl are used to it when they switch over from owo commands

[Original message by @cd36](https://discord.com/channels/741040473476694159/741047663532834827/1287675578232737802)

### PR DESCRIPTION
**Pull request by Chiffario**
Closes #850 

Testing:
image

### CODE REVIEW

**Comment by MaxOhn** [comment]
Would adding `tt`, `tc`, and `tm` for the other modes also be possible?

**Comment by Chiffario** [comment]
Didn't know how to proceed with other modes because adding `<tt/tm/tc` also suggests that `<to‘ refers to `<toposu` which isn't the case. If you don't consider this to be an issue, I'll add the other three yeah

**Comment by MaxOhn** [comment]
> Didn't know how to proceed with other modes because adding `<tt/tm/tc` also suggests that `<to` refers to `<toposu` which isn't the case. If you don't consider this to be an issue, I'll add the other three yeah

I think that's fine, no other command has an alias like that for std so I don't expect this to cause confusion.

**Comment by MaxOhn** [comment]
Thanks :)

**Pull request merged**
