### PR TITLE
Adjusted rb message content if index is specified (Issue #407)

### PR DESCRIPTION
**Pull request by Ricar415**
Solves issue https://github.com/MaxOhn/Bathbot/issues/407
Before:
<rb1  &nbsp; ```Most recent scores in Ricar_old's top100:```
<rb2  &nbsp; ```Most recent scores in Ricar_old's top100:```
<rb3  &nbsp; ```Most recent scores in Ricar_old's top100:```
<rb57 ```Most recent scores in Ricar_old's top100:```

After:
<rb1  &nbsp; ```Most recent score in Ricar_old's top100:```
<rb2 &nbsp;  ```2nd most recent score in Ricar_old's top100:```
<rb3 &nbsp;  ```3rd most recent score in Ricar_old's top100:```
<rb57 ```57th most recent score in Ricar_old's top100:```

Added to reverse argument too with "oldest".

### CODE REVIEW

**Comment by MaxOhn** [comment]
Small nit: could you replace those `.filter(...).is_some()` with `.is_some_and(...)`? Makes it a little cleaner, I should apply that everywhere sometime.

**Comment by Ricar415** [comment]
Hi!
Had some trouble with that one.
Sidenote: I noticed that using <rb0 returns just <rb1

**Comment by MaxOhn** [comment]
> Sidenote: I noticed that using <rb0 returns just <rb1

Oh right good catch, should probably use `<= 1` instead of `== 1` for those two cases then.

**Comment by MaxOhn** [comment]
Technically if someone has only one score in their top100 i.e. if `amount == 1` it should show the adjusted text as well but I think this is niche enough to just be ignored

**Comment by MaxOhn** [comment]
Thanks for looking into it!

**Pull request merged**
